name: Deploy to AWS

on:
  workflow_dispatch:

env:
  APP_NAME: Laravel
  APP_ENV: local
  APP_KEY: ${{ secrets.APP_KEY }}
  APP_DEBUG: true
  APP_URL: https://www.app.gov.co
  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: null
  LOG_LEVEL: debug
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: ''
  DB_USERNAME: ''
  DB_PASSWORD: ''
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: 120
  MEMCACHED_HOST: 127.0.0.1
  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: null
  REDIS_PORT: 6379
  MAIL_MAILER: smtp
  MAIL_HOST: ${{ vars.MAIL_HOST }}
  MAIL_PORT: ${{ vars.MAIL_PORT }}
  MAIL_USERNAME: ${{ vars.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  MAIL_ENCRYPTION: tls
  MAIL_FROM_ADDRESS: ${{ vars.MAIL_USERNAME }}
  MAIL_FROM_NAME: Laravel
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: ''
  AWS_USE_PATH_STYLE_ENDPOINT: false
  PUSHER_APP_ID: ''
  PUSHER_APP_KEY: ''
  PUSHER_APP_SECRET: ''
  PUSHER_HOST: ''
  PUSHER_PORT: 443
  PUSHER_SCHEME: https
  PUSHER_APP_CLUSTER: mt1
  VITE_PUSHER_APP_KEY: ''
  VITE_PUSHER_HOST: ''
  VITE_PUSHER_PORT: 443
  VITE_PUSHER_SCHEME: https
  VITE_PUSHER_APP_CLUSTER: mt1

jobs:
  deploy:
    runs-on:
      - codebuild-github-app-runner-project-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v2

      - name: Show Python version
        run: python3 --version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install aws-cdk-lib constructs

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CDK stack
        run: |
          cd infra
          cdk deploy --require-approval never