name: Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Variables que se pasan al CDK (las demás están hardcodeadas en el stack)
  APP_KEY: ${{ secrets.APP_KEY }}
  MAIL_HOST: ${{ vars.MAIL_HOST }}
  MAIL_PORT: ${{ vars.MAIL_PORT }}
  MAIL_USERNAME: ${{ vars.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  MAIL_FROM_ADDRESS: ${{ vars.MAIL_FROM_ADDRESS }}

jobs:
  deploy:
    runs-on:
      - codebuild-github-app-runner-project-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v2

      - name: Show Python version
        run: python3 --version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install aws-cdk-lib constructs

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy CDK stack
        run: |
          cd infra
          cdk deploy --require-approval never \
            -c app_key=${{ secrets.APP_KEY }} \
            -c mail_host=${{ vars.MAIL_HOST }} \
            -c mail_port=${{ vars.MAIL_PORT }} \
            -c mail_username=${{ vars.MAIL_USERNAME }} \
            -c mail_password=${{ secrets.MAIL_PASSWORD }} \
            -c mail_from_address=${{ vars.MAIL_FROM_ADDRESS }}